/**
 * myDoc - ICD-11 Diagnosis Codes Data
 * Populate ICD-11 codes sheet with common Kenyan diagnoses
 */

function populateICD11Codes(sheet) {
  var codes = [
    // INFECTIOUS DISEASES (50 codes)
    ['1C62.Z', 'Malaria, unspecified', 'Infectious', 'Malaria'],
    ['1C62.0', 'Plasmodium falciparum malaria', 'Infectious', 'Severe malaria'],
    ['1C62.1', 'Plasmodium vivax malaria', 'Infectious', 'Vivax malaria'],
    ['1C62.2', 'Plasmodium ovale malaria', 'Infectious', 'Ovale malaria'],
    ['1C62.3', 'Plasmodium malariae malaria', 'Infectious', 'Malariae malaria'],
    ['1C1Z', 'Tuberculosis, unspecified', 'Infectious', 'TB'],
    ['1C10', 'Pulmonary tuberculosis', 'Infectious', 'Lung TB'],
    ['1C11', 'Extrapulmonary tuberculosis', 'Infectious', 'TB outside lungs'],
    ['1A40.0', 'Typhoid fever', 'Infectious', 'Typhoid'],
    ['1A40.1', 'Paratyphoid fever A', 'Infectious', 'Paratyphoid'],
    ['1A00', 'Cholera', 'Infectious', 'Cholera'],
    ['1A01', 'Shigellosis', 'Infectious', 'Dysentery'],
    ['1A02', 'Salmonellosis', 'Infectious', 'Salmonella infection'],
    ['1A03', 'Amoebiasis', 'Infectious', 'Amoeba'],
    ['1A04', 'Giardiasis', 'Infectious', 'Giardia'],
    ['1C60', 'HIV disease', 'Infectious', 'HIV/AIDS'],
    ['1C62.Y', 'Other specified malaria', 'Infectious', 'Other malaria'],
    ['1E50', 'Acute upper respiratory infections', 'Infectious', 'URTI'],
    ['1E51', 'Acute pharyngitis', 'Infectious', 'Sore throat'],
    ['1E52', 'Acute tonsillitis', 'Infectious', 'Tonsillitis'],
    ['1E53', 'Acute laryngitis', 'Infectious', 'Laryngitis'],
    ['1E54', 'Acute sinusitis', 'Infectious', 'Sinusitis'],
    ['1F03.Z', 'Diarrhoea, unspecified', 'Infectious', 'Diarrhea'],
    ['1F00', 'Gastroenteritis', 'Infectious', 'Stomach flu'],
    ['1F01', 'Infectious gastroenteritis', 'Infectious', 'Infectious diarrhea'],
    ['9A00.0', 'Conjunctivitis, unspecified', 'Infectious', 'Pink eye'],
    ['9A01', 'Bacterial conjunctivitis', 'Infectious', 'Bacterial eye infection'],
    ['9A02', 'Viral conjunctivitis', 'Infectious', 'Viral eye infection'],
    ['1B90', 'Measles', 'Infectious', 'Measles'],
    ['1B91', 'Rubella', 'Infectious', 'German measles'],
    ['1B92', 'Chickenpox', 'Infectious', 'Chickenpox'],
    ['1B93', 'Mumps', 'Infectious', 'Mumps'],
    ['1B94', 'Whooping cough', 'Infectious', 'Pertussis'],
    ['1C30', 'Hepatitis A', 'Infectious', 'Hep A'],
    ['1C31', 'Hepatitis B', 'Infectious', 'Hep B'],
    ['1C32', 'Hepatitis C', 'Infectious', 'Hep C'],
    ['1D40', 'Scabies', 'Infectious', 'Scabies'],
    ['1D41', 'Pediculosis', 'Infectious', 'Lice'],
    ['1D42', 'Ringworm', 'Infectious', 'Fungal infection'],
    ['1D43', 'Candidiasis', 'Infectious', 'Yeast infection'],
    ['1E60', 'Pneumonia, organism unspecified', 'Infectious', 'Pneumonia'],
    ['1E61', 'Bacterial pneumonia', 'Infectious', 'Bacterial pneumonia'],
    ['1E62', 'Viral pneumonia', 'Infectious', 'Viral pneumonia'],
    ['DA0E', 'Acute bronchitis', 'Infectious', 'Bronchitis'],
    ['DA0F', 'Chronic bronchitis', 'Infectious', 'Chronic bronchitis'],
    ['1G00', 'Meningitis, unspecified', 'Infectious', 'Meningitis'],
    ['1G01', 'Bacterial meningitis', 'Infectious', 'Bacterial meningitis'],
    ['1G02', 'Viral meningitis', 'Infectious', 'Viral meningitis'],
    ['1F20', 'Helminthiasis', 'Infectious', 'Worm infection'],
    ['1F21', 'Ascariasis', 'Infectious', 'Roundworm'],
    
    // CARDIOVASCULAR (30 codes)
    ['CA40.0', 'Essential hypertension', 'Cardiovascular', 'High blood pressure'],
    ['CA40.1', 'Secondary hypertension', 'Cardiovascular', 'Secondary hypertension'],
    ['CA40', 'Hypertensive diseases', 'Cardiovascular', 'Hypertension'],
    ['BA00', 'Heart failure', 'Cardiovascular', 'Heart failure'],
    ['BA01', 'Congestive heart failure', 'Cardiovascular', 'CHF'],
    ['BA10', 'Ischaemic heart disease', 'Cardiovascular', 'Heart disease'],
    ['BA11', 'Angina pectoris', 'Cardiovascular', 'Angina'],
    ['BA20', 'Myocardial infarction', 'Cardiovascular', 'Heart attack'],
    ['BA30', 'Cardiac arrhythmia', 'Cardiovascular', 'Irregular heartbeat'],
    ['BA31', 'Atrial fibrillation', 'Cardiovascular', 'AFib'],
    ['BA40', 'Valvular heart disease', 'Cardiovascular', 'Heart valve problem'],
    ['BA50', 'Cardiomyopathy', 'Cardiovascular', 'Weak heart muscle'],
    ['BB00', 'Stroke', 'Cardiovascular', 'Stroke'],
    ['BB01', 'Ischaemic stroke', 'Cardiovascular', 'Ischemic stroke'],
    ['BB02', 'Haemorrhagic stroke', 'Cardiovascular', 'Bleeding stroke'],
    ['BB10', 'Transient ischaemic attack', 'Cardiovascular', 'Mini stroke'],
    ['BC00', 'Peripheral vascular disease', 'Cardiovascular', 'PVD'],
    ['BC01', 'Atherosclerosis', 'Cardiovascular', 'Hardened arteries'],
    ['BC10', 'Deep vein thrombosis', 'Cardiovascular', 'DVT'],
    ['BC11', 'Pulmonary embolism', 'Cardiovascular', 'Blood clot in lung'],
    ['BC20', 'Varicose veins', 'Cardiovascular', 'Varicose veins'],
    ['BD00', 'Rheumatic heart disease', 'Cardiovascular', 'Rheumatic heart'],
    ['BD01', 'Rheumatic fever', 'Cardiovascular', 'Rheumatic fever'],
    ['BE00', 'Pericarditis', 'Cardiovascular', 'Heart sac inflammation'],
    ['BE01', 'Myocarditis', 'Cardiovascular', 'Heart muscle inflammation'],
    ['BE02', 'Endocarditis', 'Cardiovascular', 'Heart lining inflammation'],
    ['CA41', 'Hypertensive heart disease', 'Cardiovascular', 'Hypertensive heart'],
    ['CA42', 'Hypertensive kidney disease', 'Cardiovascular', 'Hypertensive kidney'],
    ['CA43', 'Hypertensive crisis', 'Cardiovascular', 'Severe high BP'],
    ['CA44', 'Pre-eclampsia', 'Cardiovascular', 'Pregnancy high BP'],
    
    // ENDOCRINE & METABOLIC (25 codes)
    ['5A11', 'Type 2 diabetes mellitus', 'Endocrine', 'Diabetes type 2'],
    ['5A10', 'Type 1 diabetes mellitus', 'Endocrine', 'Diabetes type 1'],
    ['5A1Z', 'Diabetes mellitus, unspecified', 'Endocrine', 'Diabetes'],
    ['5A12', 'Gestational diabetes', 'Endocrine', 'Pregnancy diabetes'],
    ['5A13', 'Diabetic ketoacidosis', 'Endocrine', 'DKA'],
    ['5A14', 'Hypoglycaemia', 'Endocrine', 'Low blood sugar'],
    ['5A20', 'Hypothyroidism', 'Endocrine', 'Underactive thyroid'],
    ['5A21', 'Hyperthyroidism', 'Endocrine', 'Overactive thyroid'],
    ['5A22', 'Goitre', 'Endocrine', 'Enlarged thyroid'],
    ['5A23', 'Thyroiditis', 'Endocrine', 'Thyroid inflammation'],
    ['5B80', 'Obesity', 'Endocrine', 'Obesity'],
    ['5B81', 'Morbid obesity', 'Endocrine', 'Severe obesity'],
    ['5B82', 'Overweight', 'Endocrine', 'Overweight'],
    ['EK30', 'Malnutrition', 'Endocrine', 'Malnutrition'],
    ['EK31', 'Severe malnutrition', 'Endocrine', 'Severe malnutrition'],
    ['EK32', 'Kwashiorkor', 'Endocrine', 'Kwashiorkor'],
    ['EK33', 'Marasmus', 'Endocrine', 'Marasmus'],
    ['5C90', 'Gout', 'Endocrine', 'Gout'],
    ['5C91', 'Hyperuricaemia', 'Endocrine', 'High uric acid'],
    ['5D00', 'Hyperlipidaemia', 'Endocrine', 'High cholesterol'],
    ['5D01', 'Hypercholesterolaemia', 'Endocrine', 'High cholesterol'],
    ['5D02', 'Hypertriglyceridaemia', 'Endocrine', 'High triglycerides'],
    ['5E00', 'Vitamin deficiency', 'Endocrine', 'Vitamin deficiency'],
    ['5E01', 'Vitamin D deficiency', 'Endocrine', 'Vitamin D deficiency'],
    ['5E02', 'Vitamin B12 deficiency', 'Endocrine', 'B12 deficiency'],
    
    // RESPIRATORY (20 codes)
    ['CA43.Z', 'Pneumonia, organism unspecified', 'Respiratory', 'Pneumonia'],
    ['CA40', 'Asthma', 'Respiratory', 'Asthma'],
    ['CA41', 'Chronic obstructive pulmonary disease', 'Respiratory', 'COPD'],
    ['CA42', 'Emphysema', 'Respiratory', 'Emphysema'],
    ['CA44', 'Bronchiectasis', 'Respiratory', 'Bronchiectasis'],
    ['CA45', 'Pulmonary tuberculosis', 'Respiratory', 'Lung TB'],
    ['CA46', 'Pleural effusion', 'Respiratory', 'Fluid around lung'],
    ['CA47', 'Pneumothorax', 'Respiratory', 'Collapsed lung'],
    ['CA48', 'Pulmonary oedema', 'Respiratory', 'Fluid in lungs'],
    ['CA49', 'Respiratory failure', 'Respiratory', 'Respiratory failure'],
    ['CA50', 'Allergic rhinitis', 'Respiratory', 'Hay fever'],
    ['CA51', 'Chronic rhinitis', 'Respiratory', 'Chronic runny nose'],
    ['CA52', 'Nasal polyps', 'Respiratory', 'Nasal polyps'],
    ['CA53', 'Deviated nasal septum', 'Respiratory', 'Deviated septum'],
    ['CA54', 'Pharyngitis', 'Respiratory', 'Throat infection'],
    ['CA55', 'Tonsillitis', 'Respiratory', 'Tonsil infection'],
    ['CA56', 'Laryngitis', 'Respiratory', 'Voice box infection'],
    ['CA57', 'Influenza', 'Respiratory', 'Flu'],
    ['CA58', 'Common cold', 'Respiratory', 'Cold'],
    ['CA59', 'Cough', 'Respiratory', 'Cough'],
    
    // GASTROINTESTINAL (25 codes)
    ['DA90', 'Gastritis', 'Gastrointestinal', 'Stomach inflammation'],
    ['DA91', 'Peptic ulcer', 'Gastrointestinal', 'Stomach ulcer'],
    ['DA92', 'Gastric ulcer', 'Gastrointestinal', 'Stomach ulcer'],
    ['DA93', 'Duodenal ulcer', 'Gastrointestinal', 'Duodenal ulcer'],
    ['DA94', 'Gastroesophageal reflux disease', 'Gastrointestinal', 'GERD'],
    ['DA95', 'Dyspepsia', 'Gastrointestinal', 'Indigestion'],
    ['DA96', 'Appendicitis', 'Gastrointestinal', 'Appendicitis'],
    ['DA97', 'Intestinal obstruction', 'Gastrointestinal', 'Bowel obstruction'],
    ['DA98', 'Hernia', 'Gastrointestinal', 'Hernia'],
    ['DA99', 'Inguinal hernia', 'Gastrointestinal', 'Groin hernia'],
    ['DB00', 'Umbilical hernia', 'Gastrointestinal', 'Belly button hernia'],
    ['DB01', 'Haemorrhoids', 'Gastrointestinal', 'Piles'],
    ['DB02', 'Anal fissure', 'Gastrointestinal', 'Anal tear'],
    ['DB03', 'Constipation', 'Gastrointestinal', 'Constipation'],
    ['DB04', 'Diarrhoea', 'Gastrointestinal', 'Diarrhea'],
    ['DB05', 'Irritable bowel syndrome', 'Gastrointestinal', 'IBS'],
    ['DB06', 'Inflammatory bowel disease', 'Gastrointestinal', 'IBD'],
    ['DB07', 'Crohn disease', 'Gastrointestinal', 'Crohns'],
    ['DB08', 'Ulcerative colitis', 'Gastrointestinal', 'Ulcerative colitis'],
    ['DB09', 'Hepatitis', 'Gastrointestinal', 'Liver inflammation'],
    ['DB10', 'Cirrhosis', 'Gastrointestinal', 'Liver cirrhosis'],
    ['DB11', 'Fatty liver', 'Gastrointestinal', 'Fatty liver'],
    ['DB12', 'Cholecystitis', 'Gastrointestinal', 'Gallbladder inflammation'],
    ['DB13', 'Cholelithiasis', 'Gastrointestinal', 'Gallstones'],
    ['DB14', 'Pancreatitis', 'Gastrointestinal', 'Pancreas inflammation'],
    
    // GENITOURINARY (20 codes)
    ['GC08', 'Urinary tract infection, site not specified', 'Genitourinary', 'UTI'],
    ['GC09', 'Cystitis', 'Genitourinary', 'Bladder infection'],
    ['GC10', 'Pyelonephritis', 'Genitourinary', 'Kidney infection'],
    ['GC11', 'Urethritis', 'Genitourinary', 'Urethra infection'],
    ['GC12', 'Kidney stones', 'Genitourinary', 'Kidney stones'],
    ['GC13', 'Chronic kidney disease', 'Genitourinary', 'CKD'],
    ['GC14', 'Acute kidney injury', 'Genitourinary', 'Acute kidney failure'],
    ['GC15', 'Glomerulonephritis', 'Genitourinary', 'Kidney inflammation'],
    ['GC16', 'Nephrotic syndrome', 'Genitourinary', 'Nephrotic syndrome'],
    ['GC17', 'Benign prostatic hyperplasia', 'Genitourinary', 'Enlarged prostate'],
    ['GC18', 'Prostatitis', 'Genitourinary', 'Prostate infection'],
    ['GC19', 'Erectile dysfunction', 'Genitourinary', 'ED'],
    ['GC20', 'Pelvic inflammatory disease', 'Genitourinary', 'PID'],
    ['GC21', 'Vaginitis', 'Genitourinary', 'Vaginal infection'],
    ['GC22', 'Cervicitis', 'Genitourinary', 'Cervix infection'],
    ['GC23', 'Endometriosis', 'Genitourinary', 'Endometriosis'],
    ['GC24', 'Uterine fibroids', 'Genitourinary', 'Fibroids'],
    ['GC25', 'Ovarian cyst', 'Genitourinary', 'Ovarian cyst'],
    ['GC26', 'Menstrual disorders', 'Genitourinary', 'Period problems'],
    ['GC27', 'Sexually transmitted infection', 'Genitourinary', 'STI'],
    
    // MATERNAL & PREGNANCY (15 codes)
    ['9B71.0Z', 'Normal pregnancy', 'Maternal', 'Normal pregnancy'],
    ['9B71.1', 'High-risk pregnancy', 'Maternal', 'High-risk pregnancy'],
    ['9B72', 'Hyperemesis gravidarum', 'Maternal', 'Severe morning sickness'],
    ['9B73', 'Gestational hypertension', 'Maternal', 'Pregnancy high BP'],
    ['9B74', 'Pre-eclampsia', 'Maternal', 'Pre-eclampsia'],
    ['9B75', 'Eclampsia', 'Maternal', 'Eclampsia'],
    ['9B76', 'Gestational diabetes', 'Maternal', 'Pregnancy diabetes'],
    ['9B77', 'Threatened abortion', 'Maternal', 'Threatened miscarriage'],
    ['9B78', 'Miscarriage', 'Maternal', 'Miscarriage'],
    ['9B79', 'Ectopic pregnancy', 'Maternal', 'Ectopic pregnancy'],
    ['9B80', 'Placenta praevia', 'Maternal', 'Low-lying placenta'],
    ['9B81', 'Placental abruption', 'Maternal', 'Placenta separation'],
    ['9B82', 'Premature labour', 'Maternal', 'Preterm labor'],
    ['9B83', 'Postpartum haemorrhage', 'Maternal', 'Bleeding after delivery'],
    ['9B84', 'Puerperal sepsis', 'Maternal', 'Postpartum infection'],
    
    // HAEMATOLOGY (15 codes)
    ['EK0Z', 'Anaemia, unspecified', 'Haematology', 'Anemia'],
    ['EK00', 'Iron deficiency anaemia', 'Haematology', 'Iron deficiency anemia'],
    ['EK01', 'Vitamin B12 deficiency anaemia', 'Haematology', 'B12 anemia'],
    ['EK02', 'Folate deficiency anaemia', 'Haematology', 'Folate anemia'],
    ['EK03', 'Sickle cell anaemia', 'Haematology', 'Sickle cell'],
    ['EK04', 'Thalassaemia', 'Haematology', 'Thalassemia'],
    ['EK05', 'Aplastic anaemia', 'Haematology', 'Aplastic anemia'],
    ['EK06', 'Haemolytic anaemia', 'Haematology', 'Hemolytic anemia'],
    ['EK07', 'Leukaemia', 'Haematology', 'Leukemia'],
    ['EK08', 'Lymphoma', 'Haematology', 'Lymphoma'],
    ['EK09', 'Multiple myeloma', 'Haematology', 'Multiple myeloma'],
    ['EK10', 'Thrombocytopenia', 'Haematology', 'Low platelets'],
    ['EK11', 'Coagulation disorder', 'Haematology', 'Bleeding disorder'],
    ['EK12', 'Haemophilia', 'Haematology', 'Hemophilia'],
    ['EK13', 'Von Willebrand disease', 'Haematology', 'Von Willebrand'],
    
    // MUSCULOSKELETAL (20 codes)
    ['FA70', 'Arthritis, unspecified', 'Musculoskeletal', 'Arthritis'],
    ['FA71', 'Osteoarthritis', 'Musculoskeletal', 'Osteoarthritis'],
    ['FA72', 'Rheumatoid arthritis', 'Musculoskeletal', 'Rheumatoid arthritis'],
    ['FA73', 'Gout', 'Musculoskeletal', 'Gout'],
    ['FA74', 'Back pain', 'Musculoskeletal', 'Back pain'],
    ['FA75', 'Low back pain', 'Musculoskeletal', 'Lower back pain'],
    ['FA76', 'Neck pain', 'Musculoskeletal', 'Neck pain'],
    ['FA77', 'Joint pain', 'Musculoskeletal', 'Joint pain'],
    ['FA78', 'Muscle pain', 'Musculoskeletal', 'Muscle pain'],
    ['FA79', 'Fracture', 'Musculoskeletal', 'Broken bone'],
    ['FA80', 'Sprain', 'Musculoskeletal', 'Sprain'],
    ['FA81', 'Strain', 'Musculoskeletal', 'Muscle strain'],
    ['FA82', 'Dislocation', 'Musculoskeletal', 'Dislocation'],
    ['FA83', 'Tendinitis', 'Musculoskeletal', 'Tendon inflammation'],
    ['FA84', 'Bursitis', 'Musculoskeletal', 'Bursa inflammation'],
    ['FA85', 'Carpal tunnel syndrome', 'Musculoskeletal', 'Carpal tunnel'],
    ['FA86', 'Osteoporosis', 'Musculoskeletal', 'Weak bones'],
    ['FA87', 'Scoliosis', 'Musculoskeletal', 'Curved spine'],
    ['FA88', 'Herniated disc', 'Musculoskeletal', 'Slipped disc'],
    ['FA89', 'Sciatica', 'Musculoskeletal', 'Sciatica'],
    
    // NEUROLOGICAL (15 codes)
    ['8A00', 'Epilepsy', 'Neurological', 'Epilepsy'],
    ['8A01', 'Seizure disorder', 'Neurological', 'Seizures'],
    ['8A02', 'Migraine', 'Neurological', 'Migraine'],
    ['8A03', 'Tension headache', 'Neurological', 'Tension headache'],
    ['8A04', 'Cluster headache', 'Neurological', 'Cluster headache'],
    ['EE90', 'Headache', 'Neurological', 'Headache'],
    ['8A05', 'Stroke', 'Neurological', 'Stroke'],
    ['8A06', 'Transient ischaemic attack', 'Neurological', 'TIA'],
    ['8A07', 'Parkinson disease', 'Neurological', 'Parkinsons'],
    ['8A08', 'Dementia', 'Neurological', 'Dementia'],
    ['8A09', 'Alzheimer disease', 'Neurological', 'Alzheimers'],
    ['8A10', 'Multiple sclerosis', 'Neurological', 'MS'],
    ['8A11', 'Peripheral neuropathy', 'Neurological', 'Nerve damage'],
    ['8A12', 'Bell palsy', 'Neurological', 'Facial paralysis'],
    ['8A13', 'Meningitis', 'Neurological', 'Brain infection'],
    
    // DERMATOLOGY (15 codes)
    ['EA00', 'Eczema', 'Dermatology', 'Eczema'],
    ['EA01', 'Atopic dermatitis', 'Dermatology', 'Atopic dermatitis'],
    ['EA02', 'Contact dermatitis', 'Dermatology', 'Contact dermatitis'],
    ['EA03', 'Psoriasis', 'Dermatology', 'Psoriasis'],
    ['EA04', 'Acne', 'Dermatology', 'Acne'],
    ['EA05', 'Rosacea', 'Dermatology', 'Rosacea'],
    ['EA06', 'Urticaria', 'Dermatology', 'Hives'],
    ['EA07', 'Fungal skin infection', 'Dermatology', 'Fungal infection'],
    ['EA08', 'Bacterial skin infection', 'Dermatology', 'Bacterial infection'],
    ['EA09', 'Cellulitis', 'Dermatology', 'Cellulitis'],
    ['EA10', 'Abscess', 'Dermatology', 'Abscess'],
    ['EA11', 'Impetigo', 'Dermatology', 'Impetigo'],
    ['EA12', 'Warts', 'Dermatology', 'Warts'],
    ['EA13', 'Skin ulcer', 'Dermatology', 'Skin ulcer'],
    ['EA14', 'Burns', 'Dermatology', 'Burns'],
    
    // MENTAL HEALTH (10 codes)
    ['6A70', 'Depression', 'Mental Health', 'Depression'],
    ['6A71', 'Anxiety disorder', 'Mental Health', 'Anxiety'],
    ['6A72', 'Panic disorder', 'Mental Health', 'Panic attacks'],
    ['6A73', 'Post-traumatic stress disorder', 'Mental Health', 'PTSD'],
    ['6A74', 'Obsessive-compulsive disorder', 'Mental Health', 'OCD'],
    ['6A75', 'Bipolar disorder', 'Mental Health', 'Bipolar'],
    ['6A76', 'Schizophrenia', 'Mental Health', 'Schizophrenia'],
    ['6A77', 'Psychosis', 'Mental Health', 'Psychosis'],
    ['6A78', 'Substance abuse', 'Mental Health', 'Drug abuse'],
    ['6A79', 'Alcohol dependence', 'Mental Health', 'Alcoholism'],
    
    // GENERAL SYMPTOMS (10 codes)
    ['FA01', 'Abdominal pain', 'Symptoms', 'Stomach pain'],
    ['FA02', 'Chest pain', 'Symptoms', 'Chest pain'],
    ['FA03', 'Fever', 'Symptoms', 'Fever'],
    ['FA04', 'Fatigue', 'Symptoms', 'Tiredness'],
    ['FA05', 'Dizziness', 'Symptoms', 'Dizziness'],
    ['FA06', 'Nausea', 'Symptoms', 'Nausea'],
    ['FA07', 'Vomiting', 'Symptoms', 'Vomiting'],
    ['FA08', 'Weight loss', 'Symptoms', 'Weight loss'],
    ['FA09', 'Weight gain', 'Symptoms', 'Weight gain'],
    ['FA10', 'Weakness', 'Symptoms', 'Weakness']
  ];
  
  codes.forEach(function(code) {
    sheet.appendRow(code);
  });
  
  Logger.log('Populated ' + codes.length + ' ICD-11 codes');
}
